<?php
header('Content-Type: application/json; charset=utf-8');

// Tableau des questions
$idees = [
    "Quand sort GTA 6 ?",
    "Comment économiser au péage d'Arras ?",
    "Pourquoi le ciel est-il bleu ?",
    "Comment bien débuter sur Minecraft ?",
    "Quels sont les meilleurs outils pour apprendre une langue étrangère ?",
    "Quelle est la prochaine mise à jour de Fortnite ?",
    "Comment économiser sur ses courses hebdomadaires ?",
    "Quelle est la meilleure stratégie pour gagner à Clash Royale ?",
    "Comment réduire sa consommation électrique au quotidien ?",
    "Quels sont les jeux les plus attendus en 2024 ?",
    "Comment bien choisir une assurance santé ?",
    "Quelle est la meilleure configuration pour un PC gamer à petit budget ?",
    "Comment créer un budget mensuel efficace ?",
    "Quel est l'impact du café sur la santé ?",
    "Quels sont les trucs et astuces pour améliorer ses compétences sur League of Legends ?",
    "Comment trouver des promotions pour voyager moins cher ?",
    "Quel est le meilleur itinéraire pour éviter les bouchons à Lille ?",
    "Quels jeux sont gratuits sur Steam ce mois-ci ?",
    "Comment apprendre à coder sans aucune expérience préalable ?",
    "Quelle est la meilleure manière de réduire son empreinte carbone ?",
    "Pourquoi les chats adorent-ils jouer avec des cartons ?",
    "Comment gagner des V-Bucks gratuitement sur Fortnite ?",
    "Quels sont les avantages et inconvénients de travailler à distance ?",
    "Comment bien débuter dans un nouveau jeu multijoueur ?",
    "Quels sont les bienfaits du sport sur la santé mentale ?",
    "Pourquoi la pizza est-elle ronde mais les boîtes carrées ?",
    "Comment identifier un site fiable pour acheter des clés de jeu ?",
    "Quels sont les conseils pour bien s'organiser en télétravail ?",
    "Comment économiser du carburant pendant les longs trajets ?",
    "Quel est le secret pour réussir un gâteau moelleux à tous les coups ?",
    "Pourquoi les avions laissent-ils des traînées blanches dans le ciel ?",
    "Comment fonctionne un moteur de voiture électrique ?",
    "Quels sont les meilleurs jeux pour apprendre l'histoire ?",
    "Comment économiser de l'eau au quotidien ?",
    "Quelle est la meilleure technique pour apprendre une nouvelle compétence rapidement ?",
    "Pourquoi les jeux mobiles sont-ils si addictifs ?",
    "Comment trouver des promotions sur les billets d'avion ?",
    "Quelle est l'histoire derrière la création de Pokémon ?",
    "Comment optimiser l'espace dans un petit appartement ?",
    "Quels sont les effets de la méditation sur le cerveau ?",
    "Quelle est la différence entre un SSD et un HDD ?",
    "Comment bien débuter en photographie ?",
    "Quels sont les avantages de jouer aux échecs ?",
    "Pourquoi les dauphins sont-ils considérés comme intelligents ?",
    "Comment créer un site web sans expérience en codage ?",
    "Quel est le meilleur moment pour visiter Paris ?",
    "Pourquoi les jeux rétro sont-ils toujours populaires ?",
    "Comment choisir un bon casque audio ?",
    "Quelle est la différence entre l'intelligence artificielle et le machine learning ?",
    "Comment réduire le stress avant un examen ?",
    "Pourquoi les pandas sont-ils en danger d'extinction ?",
    "Comment configurer une maison connectée ?",
    "Quels sont les bienfaits du yoga sur la santé ?",
    "Comment fonctionne une blockchain ?",
    "Pourquoi certaines personnes parlent-elles en dormant ?",
    "Quelle est la meilleure méthode pour apprendre à dessiner ?",
    "Comment choisir un vélo adapté à ses besoins ?",
    "Quels sont les meilleurs podcasts pour apprendre quelque chose de nouveau ?",
    "Comment éviter les distractions lors du travail ?",
    "Pourquoi le chocolat noir est-il considéré comme bon pour la santé ?",
    "Comment préparer un road trip avec un petit budget ?",
    "Quels sont les avantages et inconvénients des voitures autonomes ?",
    "Pourquoi les étoiles scintillent-elles ?",
    "Comment fonctionne le recyclage des plastiques ?",
    "Quel est le secret d'un bon café maison ?",
    "Comment améliorer son sommeil naturellement ?",
    "Quels sont les films les plus attendus de l'année ?",
    "Pourquoi les chats ronronnent-ils ?",
    "Comment fonctionne une imprimante 3D ?",
    "Quels sont les meilleurs moyens de rester en forme chez soi ?",
    "Pourquoi les feuilles changent-elles de couleur en automne ?",
    "Comment préparer un repas équilibré rapidement ?",
    "Quels sont les bienfaits du thé vert ?",
    "Pourquoi les rêves semblent-ils parfois si réels ?",
    "Comment bien commencer une chaîne YouTube ?",
    "Quels sont les meilleurs conseils pour voyager seul ?",
    "Pourquoi les abeilles sont-elles essentielles pour l'environnement ?",
    "Comment fonctionne un panneau solaire ?",
    "Quels sont les avantages d'une alimentation végétarienne ?",
    "Comment réduire les déchets à la maison ?",
    "Pourquoi les flamants roses sont-ils roses ?",
    "Comment bien gérer son temps au travail ?",
    "Quels sont les meilleurs livres pour apprendre la programmation ?",
    "Pourquoi la Lune a-t-elle des phases ?",
    "Comment fonctionne le cerveau humain ?",
    "Quels sont les avantages de la lecture sur tablette ?",
    "Pourquoi les chiens remuent-ils la queue ?",
    "Comment apprendre à jouer d'un instrument de musique rapidement ?",
    "Quels sont les meilleurs outils pour organiser sa journée ?",
    "Pourquoi les volcans entrent-ils en éruption ?",
    "Comment bien choisir un matelas ?",
    "Quels sont les bienfaits de la course à pied ?",
    "Pourquoi les poissons ne se noient-ils pas ?",
    "Comment bien entretenir une voiture ?",
    "Quels sont les secrets pour écrire un bon roman ?",
    "Pourquoi les feuilles des plantes jaunissent-elles ?",
    "Comment fonctionne un moteur à hydrogène ?",
    "Quels sont les meilleurs endroits pour observer les étoiles ?",
    "Pourquoi les oiseaux migrent-ils ?",
    "Comment préparer une présentation percutante ?",
    "Quels sont les avantages de faire du bénévolat ?",
    "Pourquoi les montres mécaniques sont-elles si chères ?",
    "Comment éviter le gaspillage alimentaire ?",
    "Quels sont les signes d'une bonne santé mentale ?",
    "Pourquoi les tortues vivent-elles si longtemps ?",
    "Comment développer une application mobile sans expérience ?",
    "Quels sont les avantages d'apprendre une deuxième langue ?",
    "Pourquoi le son se propage-t-il plus vite dans l'eau que dans l'air ?",
    "Comment fonctionne un moteur de recherche ?",
    "Quels sont les meilleurs exercices pour renforcer les abdominaux ?",
    "Pourquoi les girafes ont-elles un long cou ?",
    "Comment économiser de l'énergie chez soi ?",
    "Quels sont les bienfaits de passer du temps dans la nature ?",
    "Pourquoi les fourmis travaillent-elles en groupe ?",
    "Comment améliorer son style vestimentaire ?",
    "Quels sont les meilleurs conseils pour gérer ses finances ?",
    "Pourquoi les baleines chantent-elles ?",
    "Comment fonctionne une montre connectée ?",
    "Quels sont les bienfaits de la marche rapide ?",
    "Pourquoi les arcs-en-ciel ont-ils plusieurs couleurs ?",
    "Comment bien choisir un appareil photo ?",
    "Quels sont les meilleurs moyens de réduire son empreinte carbone ?",
    "Pourquoi les oiseaux chantent-ils au lever du soleil ?"
];

// Renvoie une idée aléatoire au format JSON
echo json_encode($idees[array_rand($idees)]);
?>
